### PR TITLE
Login with user and password

### PR DESCRIPTION
**Pull request by Governa**
Allows the user specify the user in the config file and asks for the password when
needed.

### CODE REVIEW

**Comment by Governa** [comment]
Ok, i'll do it.

I think getpass is a system lib, isn't it?
https://docs.python.org/2/library/getpass.html

**Comment by brunetton** [comment]
Yes you're right about getpass, :+1: for you :)

**Comment by Governa** [comment]
I think I'm done.

Any comments?

**Comment by brunetton** [comment]
Thanks, I merged and changed some minor things; principally I removed the auth-type key, finaly it's redundant with key and login keys.

Should be ok in v0.3

**Pull request closed without merging**
